<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UMK9TNG" failures="1" tests="6" name="Test" time="39.627" errors="0" timestamp="2022-11-12T12:09:57 IST">
  <testcase classname="com.saucedemoTestPack.TC001_verifyLoginFunctionality" name="verifyLogin" time="0.14"/>
  <testcase classname="com.saucedemoTestPack.TC02_verify_logoutFuctionality" name="verifyLogout" time="0.661"/>
  <testcase classname="com.saucedemoTestPack.TC06_verifyAllProducts" name="verifyAllProducts" time="0.955">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.saucedemoTestPack.TC06_verifyAllProducts.verifyAllProducts(TC06_verifyAllProducts.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProducts -->
  <testcase classname="com.saucedemoTestPack.TC03_BagProduct_AddToCartFucyionality" name="BagProduct" time="0.391"/>
  <testcase classname="com.saucedemoTestPack.TC05_verify_AboutFuctionality" name="verifyaboutFuctionality" time="6.18"/>
  <testcase classname="com.saucedemoTestPack.TC04_verify_applyFilter" name="verifyFilter" time="0.653"/>
</testsuite> <!-- Test -->
